services:
  optimail-server:
    image: optimail-server
    container_name: optimail-server
    networks:
      - host
  optimail-micro-user:
    image: optimail-micro-user
    container_name: optimail-micro-user
    networks:
      - host
