services:
  optimail-server:
    image: optimail-server
    container_name: optimail-server
    network_mode: "host"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  optimail-micro-user:
    image: optimail-micro-user
    container_name: optimail-micro-user
    network_mode: "host"
